FEAT : #20 Implement file upload function
WinterSpringProject/PROJECT-PIND pull request #21
Opened 2021-02-20 06:48 UTC by JaeminKang

파일 업로드 기능을 구현하였습니다.

close #20

2021-02-20 06:55 UTC, khcho902 approved these changes

2021-02-20 07:46 UTC, gyumnnii requested changes

2021-02-20 07:46 UTC, gyumnnii commented on src/main/java/io/spring/pind/controller/UploadController.java
> +    @PostMapping("/uploadFiles")
라우터 명을 
/file
과 같이 설정하고 http method로 분리하는 것은 어떨까요?

다른 API 스펙과 통일이 안되는 것 같습니다!

2021-02-20 08:25 UTC, JaeminKang commented on src/main/java/io/spring/pind/controller/UploadController.java
> +    @PostMapping("/uploadFiles")
의견 감사합니다. 수정 진행하도록 하겠습니다!

2021-02-21 01:02 UTC, JaeminKang commented on src/main/java/io/spring/pind/controller/UploadController.java
> +    @PostMapping("/uploadFiles")
수정 완료했습니다.

2021-02-21 01:17 UTC, gyumnnii approved these changes
수고하셨습니나~

2021-02-23 02:50 UTC, Ohhong approved these changes

2021-02-23 04:47 UTC, merged