REFACTOR : #19 Refactor CRUD api of Project entity
WinterSpringProject/PROJECT-PIND pull request #24
Opened 2021-02-21 00:48 UTC by khcho902

연관관계를 추가한 Project entity에 맞추어서 Project CRUD기능을 수정하였습니다. 

close #19

2021-02-21 02:57 UTC, JaeminKang approved these changes
dto와 entity간 컨버팅 함수 위치를 이동한 것과 JPQL 쿼리문 수정하신 것 모두 확인했습니다.
수고하셨습니다.

2021-02-21 18:36 UTC, gyumnnii requested changes

2021-02-21 18:36 UTC, gyumnnii commented on src/main/java/io/spring/pind/config/SecurityConfig.java
> +                //.antMatchers("/project/*").hasRole("USER");
해당 주석이 남아있는 이유가 있을까요?

2021-02-21 18:36 UTC, gyumnnii commented on src/main/java/io/spring/pind/dto/RegionDTO.java
> +    /*
당장 사용하지 않는 코드라면
주석 처리를 하기 보단 삭제를 하는 것을 추천드립니다.

2021-02-21 18:36 UTC, gyumnnii commented on src/main/java/io/spring/pind/service/ProjectServiceImpl.java
> +           list.add(ProjectDTO.entityToDto((Project)arr[0], (Subject)arr[1], (Region)arr[2], (Long)arr[3]));
제가 자바를 잘 알진 못해서 확실하게는 말씀 못 드리지만
강제 형변환을 하는 것 보다 별도의 인터페이스를 정의하여 사용하는 방법은 없을까요?

2021-02-21 18:36 UTC, gyumnnii commented on src/main/java/io/spring/pind/service/ProjectServiceImpl.java
> -            list.add(entityToDto(project));
전체적으로 변수명/메소드명이 단순한 것 같습니다.
간단한 메소드를 작성하더라도 의미있는 변수명을 사용하는 편이 좋습니다.

해당 코드를 확장시켜서 기능을 추가한다고 가정했을 때
작성자 이외에 다른 사람이 해당 코드를 보고 직관적으로 이해하기 어려운 경우가 발생하여 코드 이해에 쓸데없이 시간을 소모할 가능성이 있습니다.

2021-02-23 01:41 UTC, khcho902 commented on src/main/java/io/spring/pind/dto/RegionDTO.java
> +    /*
넵!!! 삭제하는게 좋을거 같네요!!

2021-02-23 01:48 UTC, khcho902 commented on src/main/java/io/spring/pind/service/ProjectServiceImpl.java
> +           list.add(ProjectDTO.entityToDto((Project)arr[0], (Subject)arr[1], (Region)arr[2], (Long)arr[3]));
좀 더 나은 방법을 찾아보고 반영하도록 하겠습니다.

2021-02-23 01:50 UTC, khcho902 commented on src/main/java/io/spring/pind/service/ProjectServiceImpl.java
> -            list.add(entityToDto(project));
직관적인 이해가 가능하도록 변수명이랑 메소드명 변경하도록 하겠습니다.  
코드 살펴봐 주셔서 감사합니다~~

2021-02-26 10:51 UTC, JaeminKang approved these changes
변경하신 부분 모두 확인했습니다. 수고하셨습니다!

2021-02-26 10:52 UTC, khcho902 commented on src/main/java/io/spring/pind/config/SecurityConfig.java
> +                //.antMatchers("/project/*").hasRole("USER");
해당 주석 삭제하였습니다 !!!

2021-02-26 11:01 UTC, khcho902 commented on src/main/java/io/spring/pind/service/ProjectServiceImpl.java
> +           list.add(ProjectDTO.entityToDto((Project)arr[0], (Subject)arr[1], (Region)arr[2], (Long)arr[3]));
말씀해주신 부분을 수정하기위해 JPA관련된 내용을 찾아보았습니다. 
일단 projectRepository.getProjectList() 메소드에서 쿼리의 결과를 Object 형태로 반환하기 때문에 발생한 문제인데, 처음에는 반환하는 형태를 Object가 아닌 Entity클래스나, DTO 클래스에 맞도록 해주려고 jpql내부에 'new 명령어'나 'fetch조인', '인터페이스를 이용한 프로젝션'등을  찾아보았습니다. 
그러나 아직 jpa대해 모르는 부분이 많아서 인지 깔끔하게 해결은 하지 못하였습니다. 
추후 좀더 나은 방법을 찾아보도록 하겠습니다.

일단, ProjectDTO 클래스 내부에  Object타입의 쿼리 결과를 ProjectDTO로 변환하는 selectProjectResultToDTO() 메소드를 추가하고 이 메소드를 이용해서 변환작업을 하였습니다.

2021-02-26 11:03 UTC, gyumnnii approved these changes
고생 많으셨습니다!

2월 마지막 금요일인데 얼른 즐기러 가셔요~

2021-02-26 11:04 UTC, JaeminKang approved these changes

2021-02-28 13:57 UTC, Ohhong approved these changes

2021-02-28 14:39 UTC, merged