Issue/#30
WinterSpringProject/PROJECT-PIND pull request #33
Opened 2021-03-07 01:39 UTC by JaeminKang

채팅에 필요한 기본적인 기능과 email 인증 기능을 구현하였습니다.

채팅 기능의 경우, 프론트 팀과 협의하여 기능을 보완할 예정입니다.

close #30

2021-03-07 03:43 UTC, gyumnnii requested changes

2021-03-07 03:43 UTC, gyumnnii commented on src/main/java/io/spring/pind/websock/repository/ChatRoomRepository.java
> +}
new line 추가 부탁드려요!

2021-03-07 03:43 UTC, gyumnnii commented on src/main/java/io/spring/pind/service/EmailService.java
> +        helper.setTo(toEmail);
사용자 이메일이 유효한지 판단하는 로직은
프론트엔드에서 담당하는건가요?

2021-03-07 03:43 UTC, gyumnnii commented on src/main/java/io/spring/pind/websock/entity/ChatMessage.java
> +    }
채팅방 퇴장에 해당하는 타입은 따로 없나요?

2021-03-07 03:43 UTC, gyumnnii commented on src/main/resources/application-credentials.yml
> +    password: qhdks123!
보안과 직결되는 데이터는 숨겨주세요~

2021-03-10 04:50 UTC, JaeminKang commented on src/main/java/io/spring/pind/service/EmailService.java
> +        helper.setTo(toEmail);
넵, 이메일 유효 체크는 프론트엔드에서 담당할 계획입니다.

2021-03-10 04:51 UTC, JaeminKang commented on src/main/resources/application-credentials.yml
> +    password: qhdks123!
엄청 큰 실수네요.. 언급해주셔서 감사합니다!! 이번 풀리퀘는 취소하고, 수정해서 다시 리뷰 요청 드리겠습니다~

2021-03-10 04:52 UTC, JaeminKang commented on src/main/java/io/spring/pind/websock/repository/ChatRoomRepository.java
> +}
수정하겠습니다!

2021-03-10 04:53 UTC, JaeminKang commented on src/main/java/io/spring/pind/websock/entity/ChatMessage.java
> +    }
말씀하신대로 채팅방 퇴장 타입도 필요할 것 같습니다.
프론트엔드와 아직 협의가 되지 않은 부분이 있어, 추후에 수정하도록 하겠습니다.

2021-03-10 05:08 UTC, JaeminKang commented on src/main/java/io/spring/pind/service/EmailService.java
> +        emailcontent.append("</html>");
어떤 식으로 추상화하는게 좋을지 간단하게 설명 더 부탁드려도 될까요? ㅠㅠ
이번에 풀리퀘 날린 것은 회원 가입시 이메일 인증 요청만을 하는 코드인데, 추후에 패스워드 변경, 프로젝트 탈퇴 등을 위한 함수들을 추가로 작성할 계획이었습니다.
답변 미리 감사드립니다!!

2021-03-10 06:51 UTC, JaeminKang commented
코드에 문제가 있어 금번 풀리퀘는 취소하고, 22번, 30번 이슈를 분리해 각각 풀리퀘 날리도록 하겠습니다.

코드 리뷰해주셔서 항상 감사드립니다!!

2021-03-10 06:51 UTC, closed without merging