FEAT : #31 Implement search function on project & Add some columns to project entity
WinterSpringProject/PROJECT-PIND pull request #34
Opened 2021-03-10 06:18 UTC by khcho902

- project조회시 title, description, leader로 검색하는 기능을 추가하였습니다. 
- project entity에 startDate(시작날짜), maxParticipateNum(최대참여인원) 칼럼을 추가해두었습니니다. 

close #31

2021-03-10 07:48 UTC, gyumnnii requested changes

2021-03-10 07:48 UTC, gyumnnii commented on src/main/java/io/spring/pind/repository/search/SearchProjectRepositoryImpl.java
> +                }
type 명을 상세하게 수정하는 것은 어떨까요?
t, d는 어느정도 유추가 되지만 l은 어떤 타입인지 잘 모르겠네요

2021-03-10 07:51 UTC, khcho902 commented on src/main/java/io/spring/pind/repository/search/SearchProjectRepositoryImpl.java
> +                }
넵!!! 좀 더 보기 편하게 변경하겠습니다!!

2021-03-10 08:14 UTC, khcho902 commented on src/main/java/io/spring/pind/repository/search/SearchProjectRepositoryImpl.java
> +                }
아래와 같이 변경하였습니다!
t => title
d => description 
l => leader

2021-03-10 08:40 UTC, gyumnnii approved these changes
고생하셨습니다~

2021-03-13 06:41 UTC, JaeminKang approved these changes
깔끔하게 잘 작성하신 것 같습니다. 수고하셨습니다 👍

2021-03-13 06:41 UTC, merged